---
- name: Install dependencies
  include: install-dependencies.yml
  when: (ansible_os_family == 'RedHat') and (ansible_distribution_major_version | int == 7)

- name: Install XDR agent & cortex.conf
  include: install-xdr.yml 
  when: (ansible_os_family == 'RedHat') and (ansible_distribution_major_version | int == 7)

- name: Test XDR agent & cleanup
  include: cleanup.yml 
  when: (ansible_os_family == 'RedHat') and (ansible_distribution_major_version | int == 12)

- name: Update XDR tags
  include: update-tags.yml
  when: (ansible_os_family == 'RedHat') and (ansible_distribution_major_version | int == 7)